use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum EventRegistryError {
    // Core event errors
    EventAlreadyExists = 1,
    EventNotFound = 2,
    Unauthorized = 3,
    InvalidAddress = 4,
    InvalidFeePercent = 5,
    EventInactive = 6,
    NotInitialized = 7,
    AlreadyInitialized = 8,
    InvalidMetadataCid = 9,
    MaxSupplyExceeded = 10,
    SupplyOverflow = 11,
    TierLimitExceeds = 13,
    TierNotFound = 14,
    TierSoldOut = 15,
    SupplyUnderflow = 16,
    InvalidQuantity = 17,
    OrganizerBlacklisted = 18,
    OrgNotBlacklisted = 19,
    InvalidResaleCapBps = 20,
    InvalidPromoBps = 21,
    EventCancelled = 22,
    EventAlreadyCanceled = 23,
    InvalidGracePeriod = 24,
    EventIsActive = 25,
    // Staking / loyalty
    AlreadyStaked = 26,
    NotStaked = 27,
    InsufficientStake = 28,
    InvalidStakeAmount = 29,
    StakingNotConfigured = 30,
    NoRewardsAvailable = 31,
    InvalidRewardAmount = 32,
    AdminAlreadyExists = 33,
    CannotRemoveLast = 35,
    InvalidThreshold = 36,
    PropAlreadyExecuted = 38,
    EventNotEnded = 39,
    InvalidMilestonePlan = 41,
    RestockingFeeHigh = 42,
    InvalidTags = 43,
    ProposalExpired = 44,
    PropAlreadyApproved = 45,
    StateError = 46,
    MultisigError = 47,
    PropAlreadyCanceled = 49,
    DeadlinePastEnd = 55,
    PerUserLimitExceeded = 60,
    InvalidDeadline = 61,
    InvalidCategoryId = 71,
    AlreadyOnWaitlist = 75,
    TooManyTiers = 80,
    // TooManyIds = 81,
    /// Issue #851: payment token is not in the event's accepted_tokens list.
    TokenNotAccepted = 82,
}
