use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum EventRegistryError {
    // Core event errors
    EventAlreadyExists = 1,
    EventNotFound = 2,
    Unauthorized = 3,
    InvalidAddress = 4,
    InvalidFeePercent = 5,
    EventInactive = 6,
    NotInitialized = 7,
    AlreadyInitialized = 8,
    InvalidMetadataCid = 9,
    MaxSupplyExceeded = 10,
    SupplyOverflow = 11,
    TierLimitExceedsMaxSupply = 13,
    TierNotFound = 14,
    TierSoldOut = 15,
    SupplyUnderflow = 16,
    InvalidQuantity = 17,
    OrganizerBlacklisted = 18,
    OrganizerNotBlacklisted = 19,
    InvalidResaleCapBps = 20,
    InvalidPromoBps = 21,
    EventCancelled = 22,
    EventAlreadyCancelled = 23,
    InvalidGracePeriodEnd = 24,
    EventIsActive = 25,
    // Staking / loyalty
    AlreadyStaked = 26,
    NotStaked = 27,
    InsufficientStakeAmount = 28,
    InvalidStakeAmount = 29,
    StakingNotConfigured = 30,
    NoRewardsAvailable = 31,
    InvalidRewardAmount = 32,
    AdminAlreadyExists = 33,
    CannotRemoveLastAdmin = 35,
    InvalidThreshold = 36,
    ProposalAlreadyExecuted = 38,
    EventNotEnded = 39,
    InvalidMilestonePlan = 41,
    RestockingFeeExceedsPrice = 42,
    InvalidTags = 43,
    ProposalExpired = 44,
    ProposalAlreadyApproved = 45,
    StateError = 46,
    MultisigError = 47,
    ProposalAlreadyCancelled = 49,
    DeadlineAfterEndTime = 55,
    PerUserLimitExceeded = 60,
    InvalidDeadline = 61,
    InvalidCategoryId = 71,
    AlreadyOnWaitlist = 75,
    TooManyTiers = 80,
}
